### ISSUE TITLE
Security Policy cannot be published to the developer portal

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-operator#223]
Since recent Dashboard defect fix relating to allowing explicit policy ID - we were not able to fully test our Security Policy reconciler.

The policy logic works, but it appears that we cannot use the B64 Encoded Namespace/Name as the policy ID in the dev portal.

There is a problem with the security policy ID being B64 encoded `NAMESPACE/NAME`, in that it is impossible to publish these APIs to the developer portal.

It looks like the security policy ID MUST be a mongo ID such as `5feb72db97b81a00016cabd0` and not `ZGVmYXVsdC9odHRwYmlu`.

---

The Item is saved to the portal catalogue:

```
{
    "_id" : ObjectId("5feb72db97b81a00016cabd0"),
    "org_id" : "5fdb14e97984d60001897656",
    "apis" : [ 
        {
            "name" : "foo",
            "short_description" : "foo",
            "long_description" : "bar",
            "show" : true,
            "api_id" : "",
            "policy_id" : "ZGVmYXVsdC9odHRwYmlu",
            "documentation" : "",
            "version" : "v2",
            "is_keyless" : false,
            "config" : {
                "org_id" : "",
                "signup_fields" : [],
                "key_request_fields" : [],
                "require_key_approval" : false,
                "redirect_on_key_request" : false,
                "redirect_to" : "",
                "enable_multi_selection" : false,
                "disable_login" : false,
                "disable_signup" : false,
                "disable_auto_login" : false,
                "catalogue_login_only" : false,
                "oauth_usage_limit" : -1,
                "email" : "",
                "mail_options" : {
                    "mail_from_name" : "",
                    "mail_from_email" : "",
                    "email_copy" : {
                        "welcome_email" : {
                            "enabled" : false,
                            "subject" : "",
                            "body" : "",
                            "sign_off" : "",
                            "hide_token_data" : false
                        },
                        "key_email" : {
                            "enabled" : false,
                            "subject" : "",
                            "body" : "",
                            "sign_off" : "",
                            "hide_token_data" : false
                        },
                        "reset_password_email" : {
                            "enabled" : false,
                            "subject" : "",
                            "body" : "",
                            "sign_off" : "",
                            "hide_token_data" : false
                        }
                    }
                },
                "override" : false,
                "hashkeys" : false
            },
            "fields" : {},
            "auth_type" : "other"
        }
    ],
    "email" : ""
}
```

But we get a Dashboard Panic upon adding the API to the catalogue:
It looks like this is the catalogue listing page.

```
ERROR 2020/12/29 18:21:30.709143 panic_handler.go:26: PANIC
URL: /api/portal/catalogue
ERROR: invalid input to ObjectIdHex: "ZGVmYXVsdC9odHRwYmlu"
STACK:
goroutine 1844 [running]:
github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*Router).handlePanic(0xc00064d790, 0xc000113800, 0xc000113820, 0x1600e60, 0xc000339ac0)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:277 +0x508
github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*Router).ServeHTTP.func1(0xc00064d790, 0xc000113800)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:43 +0x6f
panic(0x1600e60, 0xc000339ac0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/TykTechnologies/tyk-analytics/vendor/gopkg.in/mgo.v2/bson.ObjectIdHex(0xc000a9c0c0, 0x14, 0x7f8a9b78c6d0, 0x0)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/gopkg.in/mgo.v2/bson/bson.go:174 +0x1a6
github.com/TykTechnologies/tyk-analytics/dashboard.KeyRequestHelper.GetPolicyIfExists(0xc000a9c0c0, 0x14, 0x1, 0xc0002b0b40)
	/src/github.com/TykTechnologies/tyk-analytics/dashboard/portal_key_request_handler.go:23 +0x59
github.com/TykTechnologies/tyk-analytics/dashboard.APIDescriptionList.Filter(0xc0002b0900, 0x1, 0x1, 0xc000aa8ea0, 0x0, 0x0, 0xc000113820)
	/src/github.com/TykTechnologies/tyk-analytics/dashboard/portal_model_api_catalogue.go:64 +0x12a
github.com/TykTechnologies/tyk-analytics/dashboard.(*APIContext).GetPortalCatalogue(0xc00068e788, 0x2024120, 0xc000113800, 0xc000113820)
	/src/github.com/TykTechnologies/tyk-analytics/dashboard/portal_api_methods.go:532 +0x157
reflect.Value.call(0x164b220, 0x1c54fb0, 0x13, 0x18d3709, 0x4, 0xc0007448f8, 0x3, 0x3, 0x1, 0x0, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x164b220, 0x1c54fb0, 0x13, 0xc0007448f8, 0x3, 0x3, 0xc000a2b4f0, 0x1, 0x40a7d5453a2865a2)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.middlewareStack.func1(0x2024120, 0xc000113800, 0xc000113820)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:139 +0x396
github.com/TykTechnologies/tyk-analytics/dashboard.(*APIContext).InstrumentationMW(0xc00068e788, 0x2024120, 0xc000113800, 0xc000113820, 0xc000359f20)
	/src/github.com/TykTechnologies/tyk-analytics/dashboard/instrumentation_helpers.go:50 +0x113
reflect.Value.call(0x1686880, 0x1c550a0, 0x13, 0x18d3709, 0x4, 0xc000744da0, 0x4, 0x4, 0x438d3c, 0xc00037de00, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x1686880, 0x1c550a0, 0x13, 0xc000744da0, 0x4, 0x4, 0x4c0680, 0x4db1ed, 0x13e)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*middlewareHandler).invoke(0xc00068b290, 0x18c8b00, 0xc00068e788, 0x16, 0x2024120, 0xc000113800, 0xc000113820, 0xc000359f20)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:159 +0x270
github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.middlewareStack.func1(0x2024120, 0xc000113800, 0xc000113820)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:148 +0x17f
github.com/TykTechnologies/tyk-analytics/dashboard.GoCraftHttphandlerFunc.func1(0x2001d20, 0xc000113800, 0xc000a5b300)
	/src/github.com/TykTechnologies/tyk-analytics/dashboard/server.go:620 +0x40
net/http.HandlerFunc.ServeHTTP(0xc000b2e9c0, 0x2001d20, 0xc000113800, 0xc000a5b300)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/TykTechnologies/tyk-analytics/vendor/github.com/TykTechnologies/nosurf.(*CSRFHandler).handleSuccess(...)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/TykTechnologies/nosurf/handler.go:180
github.com/TykTechnologies/tyk-analytics/vendor/github.com/TykTechnologies/nosurf.(*CSRFHandler).ServeHTTP(0xc000745248, 0x2001d20, 0xc000113800, 0xc000a5b300)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/TykTechnologies/nosurf/handler.go:137 +0x587
github.com/TykTechnologies/tyk-analytics/dashboard.CSRFMiddleware(0x2024120, 0xc000113800, 0xc000113820, 0xc000359f20)
	/src/github.com/TykTechnologies/ty
```

From the developer portal page when I try to browse the catalogue, I get another panic:

```
ERROR 2020/12/29 18:22:29.148397 panic_handler.go:26: PANIC
URL: /apis/
ERROR: invalid input to ObjectIdHex: "ZGVmYXVsdC9odHRwYmlu"
STACK:
goroutine 1904 [running]:
github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*Router).handlePanic(0xc0006aaf70, 0xc000244c00, 0xc000244c20, 0x1600e60, 0xc000ace870)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:277 +0x508
github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*Router).ServeHTTP.func1(0xc0006aaf70, 0xc000244c00)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:43 +0x6f
panic(0x1600e60, 0xc000ace870)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/TykTechnologies/tyk-analytics/vendor/gopkg.in/mgo.v2/bson.ObjectIdHex(0xc000b2ba80, 0x14, 0xc000312410, 0x0)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/gopkg.in/mgo.v2/bson/bson.go:174 +0x1a6
github.com/TykTechnologies/tyk-analytics/dashboard.(*PortalContext).PortalConfigSetter(0xc000a58660, 0x2024120, 0xc000244c00, 0xc000244c20, 0xc0003677a0)
	/src/github.com/TykTechnologies/tyk-analytics/dashboard/portal_context_middleware.go:201 +0x40e
reflect.Value.call(0x1686940, 0x1c55380, 0x13, 0x18d3709, 0x4, 0xc000b937d0, 0x4, 0x4, 0xc000b93880, 0x185e9a0, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x1686940, 0x1c55380, 0x13, 0xc000b937d0, 0x4, 0x4, 0x203000, 0xc000310274, 0xc00065b680)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*middlewareHandler).invoke(0xc0001999b0, 0x18919c0, 0xc000a58660, 0x16, 0x2024120, 0xc000244c00, 0xc000244c20, 0xc0003677a0)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:159 +0x270
github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.middlewareStack.func1(0x2024120, 0xc000244c00, 0xc000244c20)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:148 +0x17f
github.com/TykTechnologies/tyk-analytics/dashboard.(*PortalContext).UserDataSetter(0xc000a58660, 0x2024120, 0xc000244c00, 0xc000244c20, 0xc0003677a0)
	/src/github.com/TykTechnologies/tyk-analytics/dashboard/portal_context_middleware.go:142 +0x132
reflect.Value.call(0x1686940, 0x1c55448, 0x13, 0x18d3709, 0x4, 0xc000b93e80, 0x4, 0x4, 0x3252801, 0xc0004ea850, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x1686940, 0x1c55448, 0x13, 0xc000b93e80, 0x4, 0x4, 0x70, 0x70, 0x30)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*middlewareHandler).invoke(0xc0001998c0, 0x18919c0, 0xc000a58660, 0x16, 0x2024120, 0xc000244c00, 0xc000244c20, 0xc0003677a0)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:159 +0x270
github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.middlewareStack.func1(0x2024120, 0xc000244c00, 0xc000244c20)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:148 +0x17f
github.com/TykTechnologies/tyk-analytics/dashboard.(*PortalContext).PortalMenuGetter(0xc000a58660, 0x2024120, 0xc000244c00, 0xc000244c20, 0xc0003677a0)
	/src/github.com/TykTechnologies/tyk-analytics/dashboard/portal_context_middleware.go:35 +0x66
reflect.Value.call(0x1686940, 0x1c553e0, 0x13, 0x18d3709, 0x4, 0xc00075a488, 0x4, 0x4, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x1686940, 0x1c553e0, 0x13, 0xc000b52488, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*middlewareHandler).invoke(0xc0001997d0, 0x18919c0, 0xc000a58660, 0x16, 0x2024120, 0xc000244c00, 0xc000244c20, 0xc0003677a0)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:159 +0x270
github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.middlewareStack.func1(0x2024120, 0xc000244c00, 0xc000244c20)
	/src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:148 +0x17f
github.com/TykTechnologies/tyk-a
```

**Comment by asoorm** [comment]
Apologies - Closing because it was resolved with 3.1.1 Dashboard release.
